### ISSUE TITLE
setting host argument to localhost by default may not work for macOS

### ISSUE THREAD

**Issue by bombs-kim** [alexmojaki/birdseye#81]
[environment]
* birdseye 0.8.3
* OS: macOS High Sierra 10.13.6

`birdseye` script sets --host argument to 'localhost' by default. In my case, my socketserver couldn't recognize that name. Please refer to the discussion below.
[/gaierror-errno-8-nodename-nor-servname-provided-or-not-known-with-macos-sie](https://stackoverflow.com/questions/39970606/gaierror-errno-8-nodename-nor-servname-provided-or-not-known-with-macos-sie
)

My solution was either to change `etc/hosts file` or to set `0.0.0.0` as host argument.

**Comment by alexmojaki** [comment]
Fixed in https://github.com/alexmojaki/birdseye/commit/1f31aef8f1729172baa83264904ce0ed1f7eb49b

I wouldn't recommend using 0.0.0.0 unless you want to expose your server to the outside world.

I don't understand what you tried to show me in the link, why your localhost doesn't refer to 127.0.0.1, or why an entry like that wasn't already in your /etc/hosts.

**Comment by bombs-kim** [comment]
@alexmojaki 
Sorry I wan't clear enough on why I attached the link. I just wanted to show you that some other mac users suffer from the problem, namely, that localhost does not refer to the 127.0.0.1.
